config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'tasks', to: 'tasks#index'

  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'

  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit'
  patch 'tasks/:id', to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#destroy'

  get 'tasks/:id', to: 'tasks#show', as: 'task'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]

  def index
    @tasks = Task.all
  end

  def show; end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create!(task_params)
    redirect_to tasks_path
  end

  def edit; end

  def update
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Task Manager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container">
  <h1>Create a task</h1>
  <%= form_with model: @task do |f| %>
  <div class="mb-3">
    <%= f.label :title, {class: 'form-label'} %>
    <%= f.text_field :title, {class: 'form-control', value: @task.title} %>
  </div>

  <div class="mb-3">
    <%= f.label :details, {class: 'form-label'} %>
    <%= f.text_area :details, {class: 'form-control', value: @task.details} %>
  </div>

    <div class="mb-3">
    <%= f.check_box :completed, {class: 'form-check-input'} %>
    <%= f.label :completed, {class: 'form-check-label'} %>
  </div>

  <%= f.submit 'Edit Task', class: "btn btn-primary" %>
  <% end %>
</div>

app/views/tasks/index.html.erb
<div class="container">
<h1>My tasks</h1>
<ul class='list-group'>
  <% @tasks.each do |task| %>
  <li class='list-group-item'>
    <%= task.completed ? '☑' : '☐' %><%= link_to task.title, task_path(task) %>
    <%= link_to "🗑",
      task_path(task),
      data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
     %>
  </li>
  <% end %>
</ul>
<%= link_to "+ Add a task", tasks_new_path %>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <h1>Create a task</h1>
  <%= form_with model: @task do |f| %>
  <div class="mb-3">
    <%= f.label :title, {class: 'form-label'} %>
    <%= f.text_field :title, {class: 'form-control'} %>
  </div>

  <div class="mb-3">
    <%= f.label :details, {class: 'form-label'} %>
    <%= f.text_area :details, {class: 'form-control'} %>
  </div>

  <%= f.submit 'Create Task', class: "btn btn-primary" %>
  <% end %>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <div class="d-flex">
    <h1 class="me-auto"><%= @task.title %></h1>
    <%= link_to 'Edit task', edit_path, {class: 'btn btn-light my-3'} %>
  </div>
  <div class="alert alert-light">
    <p><%= @task.details %></p>
  </div>
  <%= @task.completed ? '☑ This task is completed' : '☐ This task is not completed yet' %><br>
  <%= link_to 'Back to list', tasks_path %>
</div>